disabled_rules: # rule identifiers to exclude from running
  - trailing_comma
  - line_length
  - todo
  - nesting

opt_in_rules:
  #- attributes

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length: 60

function_body_length:
  - 20 # warning
  - 30 # error
